apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-source-pvc
spec:
  volumeName: sonar-source-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
